### PR TITLE
Removed /throttling from the url

### PR DESCRIPTION
**Pull request by raj-dvlpr**
Hi Raj, 

Committed the Changes for removing /throttling from the UserController

### CODE REVIEW

**Review by Rajk07 — COMMENTED** [review]
Hi developer, 

Code looks good. But there are some class files are pushed. Please delete them and commit

**Comment by raj-dvlpr** [comment]
Hi Lead, 
Deleted the bin folder which contains class files. 
Regards, 
Developer.

**Comment by Rajk07** [comment]
Hi Developer, 
Now it looks good. Thanks for your effort. You can merge to main branch.

**Comment by Rajk07** [comment]
Sorry, By mistake I have Closed the pull request. Go ahead! and merge the pull request.

**Pull request merged**
